language: php
sudo: false
before_script:
  - lib/createdb.sh -u root -c test/options.php --batch --no-password-file
  - lib/createdb.sh -u root -c test/cdb-options.php --no-dbuser --batch --no-password-file
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
script:
  - test/check.sh
